// app/layout.tsx - FIXED (navbar removed)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
// Remove this import: import { Nav, NavLink } from "./components/Nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("bg-background min-h-screen font-sans antialiased", inter.variable)}>
      <body className={cn(
        "bg-background min-h-screen font-sans antialiased",
        inter.variable
      )}>
        {children}  {/* Just render children, no navbar */}
      </body>
    </html>
  );
}